// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// build_pm_cpp
NumericMatrix build_pm_cpp(const NumericVector& ext_rho, int ndemes);
RcppExport SEXP _TransPhylo2_build_pm_cpp(SEXP ext_rhoSEXP, SEXP ndemesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type ext_rho(ext_rhoSEXP);
    Rcpp::traits::input_parameter< int >::type ndemes(ndemesSEXP);
    rcpp_result_gen = Rcpp::wrap(build_pm_cpp(ext_rho, ndemes));
    return rcpp_result_gen;
END_RCPP
}
// dyn_U_cpp
double dyn_U_cpp(const NumericMatrix& ttree, const NumericVector& grid, const NumericMatrix& omega, double w_shape, double w_scale, double obs_end, double grid_delta, int host1, int deme1, int host2, int deme2, const NumericMatrix& pm);
RcppExport SEXP _TransPhylo2_dyn_U_cpp(SEXP ttreeSEXP, SEXP gridSEXP, SEXP omegaSEXP, SEXP w_shapeSEXP, SEXP w_scaleSEXP, SEXP obs_endSEXP, SEXP grid_deltaSEXP, SEXP host1SEXP, SEXP deme1SEXP, SEXP host2SEXP, SEXP deme2SEXP, SEXP pmSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type ttree(ttreeSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type grid(gridSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< double >::type w_shape(w_shapeSEXP);
    Rcpp::traits::input_parameter< double >::type w_scale(w_scaleSEXP);
    Rcpp::traits::input_parameter< double >::type obs_end(obs_endSEXP);
    Rcpp::traits::input_parameter< double >::type grid_delta(grid_deltaSEXP);
    Rcpp::traits::input_parameter< int >::type host1(host1SEXP);
    Rcpp::traits::input_parameter< int >::type deme1(deme1SEXP);
    Rcpp::traits::input_parameter< int >::type host2(host2SEXP);
    Rcpp::traits::input_parameter< int >::type deme2(deme2SEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type pm(pmSEXP);
    rcpp_result_gen = Rcpp::wrap(dyn_U_cpp(ttree, grid, omega, w_shape, w_scale, obs_end, grid_delta, host1, deme1, host2, deme2, pm));
    return rcpp_result_gen;
END_RCPP
}
// log_lik_ttree_multiparm_cpp
List log_lik_ttree_multiparm_cpp(const List& ttree_list, const NumericVector& grid, const List& fn_list, const NumericVector& off_r, const NumericVector& off_p, const NumericVector& piV, double w_shape, double w_scale, double ws_shape, double ws_scale, double obs_start, double obs_end, double grid_delta, int ndemes, const NumericMatrix& pm, const NumericVector& demes_prior);
RcppExport SEXP _TransPhylo2_log_lik_ttree_multiparm_cpp(SEXP ttree_listSEXP, SEXP gridSEXP, SEXP fn_listSEXP, SEXP off_rSEXP, SEXP off_pSEXP, SEXP piVSEXP, SEXP w_shapeSEXP, SEXP w_scaleSEXP, SEXP ws_shapeSEXP, SEXP ws_scaleSEXP, SEXP obs_startSEXP, SEXP obs_endSEXP, SEXP grid_deltaSEXP, SEXP ndemesSEXP, SEXP pmSEXP, SEXP demes_priorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type ttree_list(ttree_listSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type grid(gridSEXP);
    Rcpp::traits::input_parameter< const List& >::type fn_list(fn_listSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type off_r(off_rSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type off_p(off_pSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type piV(piVSEXP);
    Rcpp::traits::input_parameter< double >::type w_shape(w_shapeSEXP);
    Rcpp::traits::input_parameter< double >::type w_scale(w_scaleSEXP);
    Rcpp::traits::input_parameter< double >::type ws_shape(ws_shapeSEXP);
    Rcpp::traits::input_parameter< double >::type ws_scale(ws_scaleSEXP);
    Rcpp::traits::input_parameter< double >::type obs_start(obs_startSEXP);
    Rcpp::traits::input_parameter< double >::type obs_end(obs_endSEXP);
    Rcpp::traits::input_parameter< double >::type grid_delta(grid_deltaSEXP);
    Rcpp::traits::input_parameter< int >::type ndemes(ndemesSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type pm(pmSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type demes_prior(demes_priorSEXP);
    rcpp_result_gen = Rcpp::wrap(log_lik_ttree_multiparm_cpp(ttree_list, grid, fn_list, off_r, off_p, piV, w_shape, w_scale, ws_shape, ws_scale, obs_start, obs_end, grid_delta, ndemes, pm, demes_prior));
    return rcpp_result_gen;
END_RCPP
}
// log_lik_ttree_multiparm_part_cpp
List log_lik_ttree_multiparm_part_cpp(const List& ttree_list, const NumericVector& grid, const List& fn_list, const NumericVector& off_r, const NumericVector& off_p, const NumericVector& piV, double w_shape, double w_scale, double ws_shape, double ws_scale, double obs_start, double obs_end, double grid_delta, int ndemes, const NumericMatrix& pm, const NumericVector& demes_prior, NumericMatrix dyn_L, IntegerVector hosts);
RcppExport SEXP _TransPhylo2_log_lik_ttree_multiparm_part_cpp(SEXP ttree_listSEXP, SEXP gridSEXP, SEXP fn_listSEXP, SEXP off_rSEXP, SEXP off_pSEXP, SEXP piVSEXP, SEXP w_shapeSEXP, SEXP w_scaleSEXP, SEXP ws_shapeSEXP, SEXP ws_scaleSEXP, SEXP obs_startSEXP, SEXP obs_endSEXP, SEXP grid_deltaSEXP, SEXP ndemesSEXP, SEXP pmSEXP, SEXP demes_priorSEXP, SEXP dyn_LSEXP, SEXP hostsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type ttree_list(ttree_listSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type grid(gridSEXP);
    Rcpp::traits::input_parameter< const List& >::type fn_list(fn_listSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type off_r(off_rSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type off_p(off_pSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type piV(piVSEXP);
    Rcpp::traits::input_parameter< double >::type w_shape(w_shapeSEXP);
    Rcpp::traits::input_parameter< double >::type w_scale(w_scaleSEXP);
    Rcpp::traits::input_parameter< double >::type ws_shape(ws_shapeSEXP);
    Rcpp::traits::input_parameter< double >::type ws_scale(ws_scaleSEXP);
    Rcpp::traits::input_parameter< double >::type obs_start(obs_startSEXP);
    Rcpp::traits::input_parameter< double >::type obs_end(obs_endSEXP);
    Rcpp::traits::input_parameter< double >::type grid_delta(grid_deltaSEXP);
    Rcpp::traits::input_parameter< int >::type ndemes(ndemesSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type pm(pmSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type demes_prior(demes_priorSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type dyn_L(dyn_LSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type hosts(hostsSEXP);
    rcpp_result_gen = Rcpp::wrap(log_lik_ttree_multiparm_part_cpp(ttree_list, grid, fn_list, off_r, off_p, piV, w_shape, w_scale, ws_shape, ws_scale, obs_start, obs_end, grid_delta, ndemes, pm, demes_prior, dyn_L, hosts));
    return rcpp_result_gen;
END_RCPP
}
// log_likelihood_coalescence_linear_cpp
double log_likelihood_coalescence_linear_cpp(double infected_time, double final_time, double start_time, double kappa, double lambda, double branch_combs, int coalescence);
RcppExport SEXP _TransPhylo2_log_likelihood_coalescence_linear_cpp(SEXP infected_timeSEXP, SEXP final_timeSEXP, SEXP start_timeSEXP, SEXP kappaSEXP, SEXP lambdaSEXP, SEXP branch_combsSEXP, SEXP coalescenceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type infected_time(infected_timeSEXP);
    Rcpp::traits::input_parameter< double >::type final_time(final_timeSEXP);
    Rcpp::traits::input_parameter< double >::type start_time(start_timeSEXP);
    Rcpp::traits::input_parameter< double >::type kappa(kappaSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type branch_combs(branch_combsSEXP);
    Rcpp::traits::input_parameter< int >::type coalescence(coalescenceSEXP);
    rcpp_result_gen = Rcpp::wrap(log_likelihood_coalescence_linear_cpp(infected_time, final_time, start_time, kappa, lambda, branch_combs, coalescence));
    return rcpp_result_gen;
END_RCPP
}
// log_lik_ptree_given_ctree_cpp
double log_lik_ptree_given_ctree_cpp(const List& ctree_list, double kappa, double lambda, Nullable<IntegerVector> hosts);
RcppExport SEXP _TransPhylo2_log_lik_ptree_given_ctree_cpp(SEXP ctree_listSEXP, SEXP kappaSEXP, SEXP lambdaSEXP, SEXP hostsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type ctree_list(ctree_listSEXP);
    Rcpp::traits::input_parameter< double >::type kappa(kappaSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< Nullable<IntegerVector> >::type hosts(hostsSEXP);
    rcpp_result_gen = Rcpp::wrap(log_lik_ptree_given_ctree_cpp(ctree_list, kappa, lambda, hosts));
    return rcpp_result_gen;
END_RCPP
}
// num_approx_disc_multi_cpp
List num_approx_disc_multi_cpp(const NumericVector& grid, const NumericVector& off_r, const NumericVector& off_p, const NumericVector& pi, double w_shape, double w_scale, double ws_shape, double ws_scale, double obs_start, double obs_end, int ndemes, const NumericMatrix& pm);
RcppExport SEXP _TransPhylo2_num_approx_disc_multi_cpp(SEXP gridSEXP, SEXP off_rSEXP, SEXP off_pSEXP, SEXP piSEXP, SEXP w_shapeSEXP, SEXP w_scaleSEXP, SEXP ws_shapeSEXP, SEXP ws_scaleSEXP, SEXP obs_startSEXP, SEXP obs_endSEXP, SEXP ndemesSEXP, SEXP pmSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type grid(gridSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type off_r(off_rSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type off_p(off_pSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type pi(piSEXP);
    Rcpp::traits::input_parameter< double >::type w_shape(w_shapeSEXP);
    Rcpp::traits::input_parameter< double >::type w_scale(w_scaleSEXP);
    Rcpp::traits::input_parameter< double >::type ws_shape(ws_shapeSEXP);
    Rcpp::traits::input_parameter< double >::type ws_scale(ws_scaleSEXP);
    Rcpp::traits::input_parameter< double >::type obs_start(obs_startSEXP);
    Rcpp::traits::input_parameter< double >::type obs_end(obs_endSEXP);
    Rcpp::traits::input_parameter< int >::type ndemes(ndemesSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type pm(pmSEXP);
    rcpp_result_gen = Rcpp::wrap(num_approx_disc_multi_cpp(grid, off_r, off_p, pi, w_shape, w_scale, ws_shape, ws_scale, obs_start, obs_end, ndemes, pm));
    return rcpp_result_gen;
END_RCPP
}
// fast_mvrnorm_cpp
NumericVector fast_mvrnorm_cpp(const NumericVector& mu, const NumericMatrix& Sigma);
RcppExport SEXP _TransPhylo2_fast_mvrnorm_cpp(SEXP muSEXP, SEXP SigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type Sigma(SigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_mvrnorm_cpp(mu, Sigma));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_TransPhylo2_build_pm_cpp", (DL_FUNC) &_TransPhylo2_build_pm_cpp, 2},
    {"_TransPhylo2_dyn_U_cpp", (DL_FUNC) &_TransPhylo2_dyn_U_cpp, 12},
    {"_TransPhylo2_log_lik_ttree_multiparm_cpp", (DL_FUNC) &_TransPhylo2_log_lik_ttree_multiparm_cpp, 16},
    {"_TransPhylo2_log_lik_ttree_multiparm_part_cpp", (DL_FUNC) &_TransPhylo2_log_lik_ttree_multiparm_part_cpp, 18},
    {"_TransPhylo2_log_likelihood_coalescence_linear_cpp", (DL_FUNC) &_TransPhylo2_log_likelihood_coalescence_linear_cpp, 7},
    {"_TransPhylo2_log_lik_ptree_given_ctree_cpp", (DL_FUNC) &_TransPhylo2_log_lik_ptree_given_ctree_cpp, 4},
    {"_TransPhylo2_num_approx_disc_multi_cpp", (DL_FUNC) &_TransPhylo2_num_approx_disc_multi_cpp, 12},
    {"_TransPhylo2_fast_mvrnorm_cpp", (DL_FUNC) &_TransPhylo2_fast_mvrnorm_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_TransPhylo2(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
