# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

build_pm_cpp <- function(ext_rho, ndemes) {
    .Call(`_TransPhylo2_build_pm_cpp`, ext_rho, ndemes)
}

dyn_U_cpp <- function(ttree, grid, omega, w_shape, w_scale, obs_end, grid_delta, host1, deme1, host2, deme2, pm) {
    .Call(`_TransPhylo2_dyn_U_cpp`, ttree, grid, omega, w_shape, w_scale, obs_end, grid_delta, host1, deme1, host2, deme2, pm)
}

log_lik_ttree_multiparm_cpp <- function(ttree_list, grid, fn_list, off_r, off_p, piV, w_shape, w_scale, ws_shape, ws_scale, obs_start, obs_end, grid_delta, ndemes, pm, demes_prior) {
    .Call(`_TransPhylo2_log_lik_ttree_multiparm_cpp`, ttree_list, grid, fn_list, off_r, off_p, piV, w_shape, w_scale, ws_shape, ws_scale, obs_start, obs_end, grid_delta, ndemes, pm, demes_prior)
}

log_lik_ttree_multiparm_part_cpp <- function(ttree_list, grid, fn_list, off_r, off_p, piV, w_shape, w_scale, ws_shape, ws_scale, obs_start, obs_end, grid_delta, ndemes, pm, demes_prior, dyn_L, hosts) {
    .Call(`_TransPhylo2_log_lik_ttree_multiparm_part_cpp`, ttree_list, grid, fn_list, off_r, off_p, piV, w_shape, w_scale, ws_shape, ws_scale, obs_start, obs_end, grid_delta, ndemes, pm, demes_prior, dyn_L, hosts)
}

#' C++ version of log_likelihood_coalescence_linear
#' @param infected_time double
#' @param final_time double
#' @param start_time double
#' @param kappa double
#' @param lambda double
#' @param branch_combs double
#' @param coalescence int (1 if event is a coalescent event, else 0)
#'
#' @return double log-likelihood increment
log_likelihood_coalescence_linear_cpp <- function(infected_time, final_time, start_time, kappa, lambda, branch_combs, coalescence) {
    .Call(`_TransPhylo2_log_likelihood_coalescence_linear_cpp`, infected_time, final_time, start_time, kappa, lambda, branch_combs, coalescence)
}

log_lik_ptree_given_ctree_cpp <- function(ctree_list, kappa, lambda, hosts = NULL) {
    .Call(`_TransPhylo2_log_lik_ptree_given_ctree_cpp`, ctree_list, kappa, lambda, hosts)
}

num_approx_disc_multi_cpp <- function(grid, off_r, off_p, pi, w_shape, w_scale, ws_shape, ws_scale, obs_start, obs_end, ndemes, pm) {
    .Call(`_TransPhylo2_num_approx_disc_multi_cpp`, grid, off_r, off_p, pi, w_shape, w_scale, ws_shape, ws_scale, obs_start, obs_end, ndemes, pm)
}

fast_mvrnorm_cpp <- function(mu, Sigma) {
    .Call(`_TransPhylo2_fast_mvrnorm_cpp`, mu, Sigma)
}

